### ISSUE TITLE
2022 End-of-year checklist

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep#2921]
Starting a checklist. Feel free to add more items @mgxd @oesteban. I think this would be good to turn into an issue template once we're happy with it.

* [ ] Read through documentation
    * [ ] Update figures and sample artifacts (e.g., reports)
* [ ] Dependencies
    * [ ] Python: Consider bumping to newer minor release
    * [ ] Reconsider other version pins
    * [ ] Documentation dependencies; are all extensions still maintained?
* [ ] Review test and run logs
    * [ ] Address `DeprecationWarning`s and `FutureWarning`s or report upstream
* [ ] CI
    * [ ] Update configuration versions
    * [ ] Update runner images
    * [ ] Do we have redundant tests? Are they still justified?
    * [ ] Are packaging tests consistent with latest practices?
